name: Generate MMAR Modules Meta JSON
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

permissions:
  contents: write
  issues: write
  pull-requests: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
          architecture: "x64"

      - name: Setup Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyGithub
          pip install gitpython
          pip install ini-parser

      - name: Generate MMAR JSON
        run: python generate.py "${{ secrets.TOKEN }}"
        env:
          REPO_NAME: Magisk-Modules-Alt-Repo
          REPO_TITLE: Magisk Modules Alt Repo
          REPO_WEBSITE: https://github.com/Magisk-Modules-Alt-Repo
          REPO_SUPPORT: https://github.com/Magisk-Modules-Alt-Repo/json/issues
          REPO_DONATE: ""
          REPO_SUBMIT_MODULE: https://github.com/Magisk-Modules-Alt-Repo/submission
          REPO_SCOPE: mmar
          REPO_EXTRA_TRACKS: ""
          GIT_TOKEN: "${{ secrets.TOKEN }}"

      - name: Generate GMR JSON
        run: python generate.py "${{ secrets.TOKEN }}"
        env:
          REPO_NAME: Googlers-Repo
          REPO_TITLE: Googlers Magisk Repo
          REPO_WEBSITE: https://github.com/Googlers-Repo
          REPO_SUPPORT: https://github.com/Googlers-Repo/json/issues
          REPO_DONATE: ""
          REPO_SUBMIT_MODULE: ""
          REPO_SCOPE: gmr
          REPO_EXTRA_TRACKS: gmr-tracks
          
          GIT_TOKEN: "${{ secrets.TOKEN }}"

      - name: Generate MMR JSON
        run: python generate.py "${{ secrets.TOKEN }}"
        env:
          REPO_NAME: Magisk-Modules-Repo
          REPO_TITLE: Magisk Modules Repo (Official)
          REPO_WEBSITE: https://github.com/Magisk-Modules-Repo
          REPO_SUPPORT: ""
          REPO_DONATE: ""
          REPO_SUBMIT_MODULE: ""
          REPO_SCOPE: mmr
          REPO_EXTRA_TRACKS: ""
          GIT_TOKEN: "${{ secrets.TOKEN }}"

      - name: Setup Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Commit Changes
        run: |
          git add .
          git commit -m "Update mirrors" || true
          git push || true
